#! /usr/bin/env node

/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/

/*
  This is a command-line utility to set the TxDelay on a KISS interface
*/
var path=require('path');
var util=require('util');
const utilsForAprs=require("utils-for-aprs");
const SerialKISSFrameEndpoint=utilsForAprs.SerialKISSFrameEndpoint;
const SocketKISSFrameEndpoint=utilsForAprs.SocketKISSFrameEndpoint;

var opt=require('node-getopt').create([
  ['', 'baud[=BAUD]', 'baud rate']
]).bindHelp().parseSystem();

if (opt.argv.length != 2) {
  console.log("Usage: setTxDelay <device> <delay-in-ms> [--baud=BAUD]");
  return;
}

var device=opt.argv[0];
var delay=opt.argv[1];
var baud= opt.options.baud?parseInt(opt.options.baud):1200

/*
  If the device is formatted as a TCP endpoint, open up a TCPEndpoint,
  otherwise make it a serial endpoint.
*/
var targetEndpoint=null;
var res=/([^\:]+):([0-9]+)/.exec(device);
if (res) {
  var host=res[1];
  var port=res[2];
  targetEndpoint=new SocketKISSFrameEndpoint();
  targetEndpoint.host=host;
  targetEndpoint.port=port;
} else {
  targetEndpoint=new SerialKISSFrameEndpoint(options.device, {baudRate: baud});
}

targetEndpoint.on("listen", message => console.log(message));
targetEndpoint.on("connect", conn => {
  console.log("Connected to target endpoint.");
  var delayValue=Math.round(parseInt(delay)/10.0);
  var txDelayFrame=Buffer.from([0x01, delayValue]);
  var emptyFrame=Buffer.from([]);
  const writeData=function() {

    conn.data(txDelayFrame);
    console.log("Wrote the txDelayFrame, delayValue=" + delayValue);
    setTimeout(()=>{
      process.exit(0);
    }, 1000);
  };
  writeData();
});
targetEndpoint.on("error", message => console.log(message));

targetEndpoint.enable();
